### ISSUE TITLE
About SPSANN Package

### ISSUE THREAD

**Issue by yancong723** [samuel-rosa/spsann#18]
In oder to finish my paper,I plan to use simulated annealing method and learn R about SPSANN. I have got some problems,however,it is very abstract when I read help document.

1.    How users aggregate the objective functions into a single utility function？Such as several optimMSSD and optimMKV.

2.    How understand chains and chain.length? How should I set the parameters in scheduleSPSANN.

3.    What is the minmaxPareto function used for? What's the difference between minmaxPareto and aggregating the objective functions into a single utility function?

**Comment by OrdinarySK** [comment]
Can we communicate? Me too CUGer. Can we add a contact？

**Comment by yancong723** [comment]
Of course !You can give me you cantact.
We can communicate with wechat(18600792010),I am a Chinese.

**Comment by OrdinarySK** [comment]
Get

**Comment by OrdinarySK** [comment]
It is not find user to search your phone number in wechat. My Wechat (18571999690).

**Comment by samuel-rosa** [comment]
Hi @OrdinarySK and @yancong723. Sorry for the late reply. I have been dealing with health problems and will look into your question ASAP.

**Comment by samuel-rosa** [comment]
@OrdinarySK @yancong723 the only way for you to aggregate the two objective functions MSSD and MKV into a single utility function is by implementing the objective functions yourself and optimizing the sample configuration using `optimUSER`.

**Comment by samuel-rosa** [comment]
@OrdinarySK @yancong723 I agree that I need to improve the documentation. For you to fully understand the meaning of `minmaxPareto` please refer to the following papers:

* Marler, R. T. & Arora, J. S. The weighted sum method for multi-objective optimization: new insights. Structural and Multidisciplinary Optimization, Springer Science + Business Media, 2009, 41, 853-862.
* Marler, R. T. & Arora, J. S. Function-transformation methods for multi-objective optimization. Engineering Optimization, Informa UK Limited, 2005, 37, 551-570.
* Marler, R. T. & Arora, J. S. Survey of multi-objective optimization methods for engineering. Structural and Multidisciplinary Optimization, Springer Science + Business Media, 2004, 26, 369-395.

**Comment by samuel-rosa** [comment]
@OrdinarySK @yancong723 again, I agree that I have to improve the documentation of this topic. For now, I recommend you to read the following papers to understand the meaning of `chains` and `chain.length`:

* Ingber, L. Simulated annealing: practice versus theory. Mathematical and Computer Modelling, Elsevier BV, 1993, 18, 29-57.
* Andrieu, C.; Freitas, N.; Doucet, A. & Jordan, M. I. An introduction to MCMC for machine learning. Machine Learning, 2003, 50, 5-43.

Please note that setting `chains`, i.e. the number of Markov chains has to be done by trial and error because it depends on your study setting. So, start with the default and see if the optimization stabilizes. Otherwise you'll have to increase the number of chains. However, with respect to `chain.length`, you can generally use the default value.
